### PR TITLE
CI build

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by hannesa2** [comment]
CI doesn't start, I guess you have to enable Github actions to make it work
image

**Comment by Dimowner** [comment]
All actions was enabled. I din't change anything.
git_actions

**Comment by hannesa2** [comment]
Yes, I observed it in other repo, that it works first, when it's merged to master.
I've no clue why.

But you can see a running example here https://github.com/hannesa2/AudioRecorder/pull/5

**Comment by Qin9fung0124** [comment]
> CI doesn't start, I guess you have to enable Github actions to make it work
> image

**Comment by hannesa2** [comment]
A pull request which introduce this doesn't work by design. Merge it and you will see how it works. 
Otherwise please close it, to let me know that you are not interested

**Comment by Dimowner** [comment]
Not relevant for now

**Pull request closed without merging**
